# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 17:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('VALORIZA PROPIEDAD RAIZ', 'Valoriza Propiedad Ra\xedz'), ('DECOFACHADAS', 'Decofachadas.'), ('INVERSIONES HD GLOBAL', 'Inversiones HD Global'), ('MONTAJES ELECTRICOS', 'Montajes El\xe9ctricos'), ('SOLUCIONES EN ICOPOR', 'Soluciones en Icopor'), ('VELAYA CONSTRUCCIOENS', 'Velaya Construcciones'), ('FLOTANTES', 'Flotantes')], max_length=7)),
                ('fecha_elaboracion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Elaboraci\xf3n')),
                ('desde', models.DateField(default=datetime.date.today)),
                ('hasta', models.DateField(default=datetime.date.today)),
                ('acc_laboral', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, verbose_name='Accidentes Laborales')),
                ('inc_laboral', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, verbose_name='Incidentes Laborales')),
                ('licencias', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6)),
                ('memorandos', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, verbose_name='Memorandos o Llamados de atenci\xf3n')),
                ('suspenciones', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6)),
                ('pregunta', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='\xbfHubo incapacidades?')),
                ('incapacidad', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Enfermedad General'), (2, 'Accidente Laboral'), (3, 'Licencia de Paternidad'), (4, 'Licencia de Maternidad'), (5, 'Enfermedad Laboral')], max_length=9, verbose_name='Tipo de Incapacidad')),
                ('can_incapacidades', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, verbose_name='Cantidad de incapacidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
