# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_ejecucion_epp_2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha l\xedmite de ejecuci\xf3n para la acci\xf3n 2'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_ejecucion_epp_3',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha l\xedmite de ejecuci\xf3n para la acci\xf3n 3'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_ejecucion_epp_4',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha l\xedmite de ejecuci\xf3n para la acci\xf3n 4'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_ejecucion_epp_5',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha l\xedmite de ejecuci\xf3n para la acci\xf3n 5'),
        ),
    ]
