# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='acc_laboral',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Accidentes Laborales'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='can_incapacidades',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de Incapacidades'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='inc_laboral',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Incidentes Laborales'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='licencias',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
