# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanal', '0002_auto_20180404_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='memorandos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Memorandos o Llamados de atenci\xf3n'),
        ),
    ]
